config/routes.rb
Digg::Application.routes.draw do
  resources :redishashes do
    member do
      post "save_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :stringlists

  resources :objecteds do
    member do
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :records do
    member do
      post "save_redis_value"
      get "edit_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :products do
    member do
      post "save_redis_value"
      get "edit_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :redis_infos do
    collection do
      get "export"
      get "import"
      get 'index'
      get 'graph'
      get 'terminal'
      post 'configuration'
      get 'load_redis'
    end
  end

  resources :twitters do
    collection do
      get "init_data"
      get "index"
      get "remove_friend"
      get "add_post"
      get "add_friend"
    end
  end

  root :to => 'redis_infos#index'

end

app/models/objected.rb
class Objected < Record
  paginates_per 10
  attr_accessible :redis_value, :score

  def redis_value
    Redis.current.zrange(self.redis_key, 0, -1).join(",")
  end
end

app/controllers/objecteds_controller.rb
class ObjectedsController < ApplicationController
  # GET /zsets
  # GET /zsets.json
  def index
    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis Sorted Set", "/objecteds"
    if params[:query]
      @zsets = Objected.where("name like ?", "%"+params[:query]+"%").page params[:page]
    else
      @zsets = Objected.page params[:page]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zsets }
    end
  end

  # GET /zsets/1
  # GET /zsets/1.json
  def show
    @zset = Objected.find(params[:id])

    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis Sorted Set", "/objecteds"
    add_breadcrumb "#{@zset.redis_key}", "/objecteds/#{@zset.id}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zset }
    end
  end

  # GET /zsets/new
  # GET /zsets/new.json
  def new
    @zset = Objected.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zset }
    end
  end

  # GET /zsets/1/edit
  def edit
    @zset = Objected.find(params[:id])
    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis Sorted Set", "/objecteds"
    add_breadcrumb "#{@zset.redis_key}", "/objecteds/#{@zset.id}"
  end

  # POST /zsets
  # POST /zsets.json
  def create
    value = params[:objected].except "redis_value"
    @zset = Objected.new(value)

    respond_to do |format|
      if @zset.save
        Redis.current.zadd(@zset.redis_key, params[:objected][:score], params[:objected][:redis_value])
        
        format.html { redirect_to @zset, notice: 'Redis zset was successfully created.' }
        format.json { render json: @zset, status: :created, location: @objected }
      else
        format.html { render action: "new" }
        format.json { render json: @zset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zsets/1
  # PUT /zsets/1.json
  def update
    @zset = Objected.find(params[:id])

    respond_to do |format|
      if @zset.update_attributes(params[:zset])
        format.html { redirect_to @zset, notice: 'Redis sorted set was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zsets/1
  # DELETE /zsets/1.json
  def destroy
    @zset = Objected.find(params[:id])
    @zset.destroy

    respond_to do |format|
      format.html { redirect_to objected_path }
      format.json { head :no_content }
    end
  end

  def add_redis_value
    @zset = Objected.find(params[:id]) 
    Redis.current.zadd(@zset.redis_key, params[:score], params[:value])

    respond_to do |format|
      format.html { redirect_to @zset, notice: 'Score and Value was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def destroy_redis_value
    @zset = Objected.find(params[:id]) 
    Redis.current.zrem(@zset.redis_key, params[:value])

    respond_to do |format|
      format.html { redirect_to edit_objected_path, notice: 'Value was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/objecteds_helper.rb
module ObjectedsHelper
end

app/views/objecteds/_form.html.erb
<%= form_for @zset, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Redis List</legend>

    <div class="control-group">
      <%= f.label "key", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label "Score", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :score, :class => 'text_field', :placeholder => "请输入数字", :onKeypress => "return (/[0-9.]/.test(String.fromCharCode(event.keyCode)))" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label "Value", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :redis_value, :class => 'text_area', :placeholder => "以逗号分割" %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', objecteds_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/objecteds/edit.html.erb
<h4>Key : <%= @zset.redis_key %></h4>
<table class="table table-condensed">
  <tbody>
    <tr>
      <td style="width: 30%">Type</td>
      <td><%= @zset.redis_type %></td>
    </tr>
    <tr>
      <td style="width: 30%">TTL</td>
      <td><%= @zset.ttl %></td>
    </tr>
    <tr>
      <td style="width: 30%">Encoding</td>
      <td><%= "ziplist" %></td>
    </tr>
    <tr>
      <td style="width: 30%">Size</td>
      <td><%= Redis.current.zcard @zset.redis_key %></td>
    </tr>
  </tbody>
</table>

<div class="widget">
  <div class="header">
    <h4>Values</h4>
  </div>
  <table class="table condensed-table" id="config-table">
    <tbody>
      <% values = Redis.current.zrangebyscore(@zset.redis_key, 0, Float::MAX,{:withscores=>true}) %>
      <% (0..values.size-1).step(2) do |a|%>
        <tr>
          <td style="width: 30%"><b>score = <%= values.slice(a,2)[1] %></b></td>
          <td>
            <div id=<%= values.slice(a,2)[0] %>><%= values.slice(a,2)[0] %></div>
          </td>
          <td>
            <%= link_to "Delete", {:action => "destroy_redis_value", :id => @zset.id, :value => values.slice(a,2)[0], :controller => :objecteds}, :confirm => "Are you sure?" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="btns">
    <button class="btn btn-primary" id="add-value">Add Value</button>
    <%= link_to "Back", objecteds_path, {:class => "btn btn-primary"} %>
  </div>
</div>

<div class='modal hide' id='add-value-confirm'>
  <div class='modal-header'>
    <a class='close' data-dismiss="modal">x</a>
    <h3>Add Value</h3>
  </div>
  <div class='modal-body'>
    <form class="well">
      <label>Score</label>
      <input onKeypress="return (/[\d.]/.test(String.fromCharCode(event.keyCode)))" type="text" class="span3" id="zset_score_input">
      <label>Value</label>
      <input type="text" class="span3 input-medium" id="zset_value_input">
    </form>
  </div>
  <div class='modal-footer'>
    <button class='btn btn-secondary' id='add-value-cancel-btn'>Cancel</button>
    <button class='btn btn-primary' id='add-value-confirm-btn'>Submit</button>
  </div>
</div>

<script type='text/javascript'>
  $('#add-value').click(function() {
    $('#add-value-confirm').modal({
      backdrop: true,
      keyboard: true
    });
  });

  $('#add-value-cancel-btn').click(function(){
    $('#add-value-confirm').modal('hide');
  });

  $('#add-value-confirm-btn').click(function() {
    var id = <%= @zset.id %>;
    var score = document.getElementById("zset_score_input").value;
    var value = document.getElementById("zset_value_input").value;
    $.ajax({
      url     : 'add_redis_value?value='+value+'&score='+score+'&id='+id,
      success : function(){
        $('#add-value-confirm').modal('hide');
         window.location.reload();
      }
    });
  });
    
</script>

app/views/objecteds/index.html.erb
<h1>Redis Sorted Set</h1>
<form class="navbar-search pull-right"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
  <span id='filters_box'></span>
  <hr class='filters_box' style='display:none'>
  <input type="search" name="query" class="input-small" placeholder="Search.."><button style="margin-bottom:8px;" class="btn btn-primary" data-disable-with="<i class='icon-white icon-refresh'></i> Refresh" type="submit"><i class="icon-white icon-refresh"></i>Click</button>
</form>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
      <th>Type</th>
      <th>Size</th>
      <th>TTL</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @zsets.each do |zset| %>
      <tr>
        <td><%= link_to zset.redis_key, objected_path(zset) %></td>
        <td><%= truncate zset.redis_value %></td>
        <td><%= zset.redis_type %></td>
        <td><%= Redis.current.zcard zset.redis_key %></td>
        <td><%= zset.ttl %></td>
        <td><%= time_ago_in_words zset.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_objected_path(zset), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', objected_path(zset), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @zsets, :theme => 'boot' %>

<%= link_to 'New', new_objected_path, :class => 'btn btn-primary' %>

app/views/objecteds/show.html.erb
<h1>Redis Sorted Set</h1>

<fieldset>
  <dl>
    <dt class="key_field label string_type"><label>Key<dd><pre class="prettyprint"><%= @zset.redis_key %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>Value<dd><pre class="prettyprint"><%= @zset.redis_value %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>Type<dd><pre class="prettyprint"><%= @zset.redis_type %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>TTL<dd><pre class="prettyprint"><%= @zset.ttl %></dd></pre></label></dt>
  </dl>
</fieldset>

<div class="form-actions">
  <%= link_to 'Back', objecteds_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_objected_path(@zset), :class => 'btn' %>
  <%= link_to 'Delete', objected_path(@zset), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>