config/routes.rb
Digg::Application.routes.draw do
  resources :redishashes do
    member do
      post "save_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :stringlists

  resources :objecteds do
    member do
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :records do
    member do
      post "save_redis_value"
      get "edit_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :products do
    member do
      post "save_redis_value"
      get "edit_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :redis_infos do
    collection do
      get "export"
      get "import"
      get 'index'
      get 'graph'
      get 'terminal'
      post 'configuration'
      get 'load_redis'
    end
  end

  resources :twitters do
    collection do
      get "init_data"
      get "index"
      get "remove_friend"
      get "add_post"
      get "add_friend"
    end
  end

  root :to => 'redis_infos#index'

end

app/models/stringlist.rb
class Stringlist < Record
  paginates_per 10

  attr_accessible :redis_value

  def redis_value
    Redis.current.get(self.redis_key)
  end

  def redis_value=(str)
    Redis.current.set(self.redis_key, str)
  end
end

app/controllers/stringlists_controller.rb
class StringlistsController < ApplicationController

  # GET /stringlists
  # GET /stringlists.json
  def index
    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis String", "/stringlists"

    if params[:query]
      @stringlists = Stringlist.where("name like ?", "%"+params[:query]+"%").page params[:page]
    else
      @stringlists = Stringlist.page params[:page]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stringlists }
    end
  end

  # GET /stringlists/1
  # GET /stringlists/1.json
  def show
    @stringlist = Stringlist.find(params[:id])

    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis String", "/stringlists"
    add_breadcrumb "#{@stringlist.redis_key}", "/stringlists/#{@stringlist.id}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stringlist }
    end

  end

  # GET /stringlists/new
  # GET /stringlists/new.json
  def new
    @stringlist = Stringlist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stringlist }
    end
  end

  # GET /stringlists/1/edit
  def edit
    @stringlist = Stringlist.find(params[:id])

    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis String", "/stringlists"
    add_breadcrumb "#{@stringlist.redis_key}", "/stringlists/#{@stringlist.id}"
  end

  # POST /stringlists
  # POST /stringlists.json
  def create
    @stringlist = Stringlist.new(params[:stringlist])

    respond_to do |format|
      if @stringlist.save
        @stringlist.redis_value = params[:stringlist][:redis_value]
        format.html { redirect_to @stringlist, notice: 'Redis String was successfully created.' }
        format.json { render json: @stringlist, status: :created, location: @stringlist }
      else
        format.html { render action: "new" }
        format.json { render json: @stringlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stringlists/1
  # PUT /stringlists/1.json
  def update
    @stringlist = Stringlist.find(params[:id])

    respond_to do |format|
      if @stringlist.update_attributes(params[:stringlist])
        format.html { redirect_to @stringlist, notice: 'Stringlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stringlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stringlists/1
  # DELETE /stringlists/1.json
  def destroy
    @stringlist = Stringlist.find(params[:id])
    Redis.current.del @stringlist.redis_key
    @stringlist.destroy

    respond_to do |format|
      format.html { redirect_to stringlists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stringlists_helper.rb
module StringlistsHelper
end

app/views/stringlists/_form.html.erb
<%= form_for @stringlist, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Redis String</legend>

    <div class="control-group">
      <%= f.label "Key", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label "Value", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :redis_value, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', stringlists_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/stringlists/edit.html.erb
<%= render :partial => 'form' %>

app/views/stringlists/index.html.erb
<h1>Redis String</h1>

<form class="navbar-search pull-right"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
  <span id='filters_box'></span>
  <hr class='filters_box' style='display:none'>
  <input type="search" name="query" class="input-small" placeholder="Search.."><button style="margin-bottom:8px;" class="btn btn-primary" data-disable-with="<i class='icon-white icon-refresh'></i> Refresh" type="submit"><i class="icon-white icon-refresh"></i>Click</button>
</form>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
      <th>type</th>
      <th>size</th>
      <th>TTL</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @stringlists.each do |stringlist| %>
      <tr>
        <td><%= link_to stringlist.redis_key, stringlist_path(stringlist) %></td>
        <td><%= truncate stringlist.redis_value %></td>
        <td><%= stringlist.redis_type %></td>
        <td><%= Redis.current.strlen stringlist.redis_key %></td>
        <td><%= stringlist.ttl %></td>
        <td><%= time_ago_in_words stringlist.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_stringlist_path(stringlist), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', stringlist_path(stringlist), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @stringlists, :theme => 'boot' %>

<%= link_to 'New', new_stringlist_path, :class => 'btn btn-primary' %>

app/views/stringlists/show.html.erb
<h1>Stringlist</h1>
<fieldset>
  <dl>
    <dt class="key_field label string_type"><label>Key<dd><pre class="prettyprint"><%= @stringlist.redis_key %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>Value<dd><pre class="prettyprint"><%= @stringlist.redis_value %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>Type<dd><pre class="prettyprint"><%= @stringlist.redis_type %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>Size<dd><pre class="prettyprint"><%= Redis.current.strlen @stringlist.redis_key %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>TTL<dd><pre class="prettyprint"><%= @stringlist.ttl %></dd></pre></label></dt>
  </dl>
</fieldset>

<div class="form-actions">
  <%= link_to 'Back', stringlists_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_stringlist_path(@stringlist), :class => 'btn' %>
  <%= link_to 'Delete', stringlist_path(@stringlist), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>