config/routes.rb
Digg::Application.routes.draw do
  resources :redishashes do
    member do
      post "save_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :stringlists

  resources :objecteds do
    member do
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :records do
    member do
      post "save_redis_value"
      get "edit_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :products do
    member do
      post "save_redis_value"
      get "edit_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :redis_infos do
    collection do
      get "export"
      get "import"
      get 'index'
      get 'graph'
      get 'terminal'
      post 'configuration'
      get 'load_redis'
    end
  end

  resources :twitters do
    collection do
      get "init_data"
      get "index"
      get "remove_friend"
      get "add_post"
      get "add_friend"
    end
  end

  root :to => 'redis_infos#index'

end

app/models/redishash.rb
class Redishash < Record
  attr_accessible :redis_value

  def redis_value
    value = Redis.current.hvals(self.redis_key)
    value.empty? ? nil : value
  end
end

app/controllers/redishashes_controller.rb
class RedishashesController < ApplicationController
  # GET /redishashes
  # GET /redishashes.json
  def index
    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis Hash", "/redishashes"

    if params[:query]
      @redishashes = Redishash.where("name like ?", "%"+params[:query]+"%").page(params[:page])
    else
      @redishashes = Redishash.page params[:page]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @redishashes }
    end
  end

  # GET /redishashes/1
  # GET /redishashes/1.json
  def show
    @redishash = Redishash.find(params[:id])

    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis Hash", "/redishashes"
    add_breadcrumb "#{@redishash.redis_key}", "/redishashes/#{@redishash.id}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @redishash }
    end
  end

  # GET /redishashes/new
  # GET /redishashes/new.json
  def new
    @redishash = Redishash.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @redishash }
    end
  end

  # GET /redishashes/1/edit
  def edit
    @redishash = Redishash.find(params[:id])

    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis Hash", "/redishashes"
    add_breadcrumb "#{@redishash.redis_key}", "/redishashes/#{@redishash.id}"
  end

  # POST /redishashes
  # POST /redishashes.json
  def create
    value = params[:redishash].except "redis_value"
    @redishash = Redishash.new(value)

    respond_to do |format|
      if @redishash.save
        
        # 容错性!
        # HSETNX nosql key-value-store redis
        params[:redishash][:redis_value].split("\r\n").each do |field_value|
          Redis.current.hsetnx(@redishash.redis_key, field_value.split(",")[0], field_value.split(",")[1])
        end

        format.html { redirect_to @redishash, notice: 'Redishash was successfully created.' }
        format.json { render json: @redishash, status: :created, location: @redishash }
      else
        format.html { render action: "new" }
        format.json { render json: @redishash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /redishashes/1
  # PUT /redishashes/1.json
  def update
    @redishash = Redishash.find(params[:id])

    respond_to do |format|
      if @redishash.update_attributes(params[:redishash])
        @redishash.redis_value = params[:redishash][:redis_value]
        format.html { redirect_to @redishash, notice: 'Redishash was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @redishash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redishashes/1
  # DELETE /redishashes/1.json
  def destroy
    @redishash = Redishash.find(params[:id])
    Redis.current.del @redishash.redis_key
    @redishash.destroy

    respond_to do |format|
      format.html { redirect_to redishashes_url }
      format.json { head :no_content }
    end
  end

  def save_redis_value
    @redishash = Redishash.find(params[:id]) 
    Redis.current.hmset(@redishash.redis_key, params[:field], params[:value])

    render :text => params[:value] 
  end

  def add_redis_value
    @redishash = Redishash.find(params[:id]) 
    Redis.current.hsetnx(@redishash.redis_key, params[:field], params[:value])

    respond_to do |format|
      format.html { redirect_to edit_redishash_path, notice: 'Field and Value was successfully added.' }
      format.json { head :no_content }
    end
  end

  def destroy_redis_value
    @redishash = Redishash.find(params[:id]) 
    Redis.current.hdel(@redishash.redis_key, params[:field])

    respond_to do |format|
      format.html { redirect_to edit_redishash_path, notice: 'Field and Value were successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/redishashes_helper.rb
module RedishashesHelper
end

app/views/redishashes/_form.html.erb
<%= form_for @redishash, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Redis Hash</legend>

    <div class="control-group">
      <%= f.label "key", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label "Value", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :redis_value, :class => 'text_area', :placeholder => "以逗号分割,换行表示新增field和value" %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', redishashes_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/redishashes/edit.html.erb
<h4>Key : <%= @redishash.redis_key %></h4>
<table class="table table-condensed">
  <tbody>
    <tr>
      <td style="width: 30%">Type</td>
      <td><%= @redishash.type %></td>
    </tr>
    <tr>
      <td style="width: 30%">TTL</td>
      <td><%= @redishash.ttl %></td>
    </tr>
    <tr>
      <td style="width: 30%">Encoding</td>
      <td><%= "zipmap" %></td>
    </tr>
    <tr>
      <td style="width: 30%">Size</td>
      <td><%= @redishash.redis_value.split(',').size %></td>
    </tr>
  </tbody>
</table>

<div class="widget">
  <div class="header">
    <h4>Fields and Values</h4>
  </div>
  <table class="table condensed-table" id="config-table">
    <tbody>
      <% Redis.current.hkeys(@redishash.redis_key).each do |field| %>
        <tr>
          <td style="width: 30%"><%= field %></td>
          <td>
            <div class="editable" id=<%= field %>><%= Redis.current.hmget(@redishash.redis_key, field)[0] %></div>
          </td>
          <td>
            <%= link_to "Delete", {:action => "destroy_redis_value", :id => @redishash.id, :field => field, :controller => :redishashes}, :confirm => "Are you sure?" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="btns">
    <button class="btn btn-primary" id="add-value">Add Value</button>
    <%= link_to "Back", redishashes_path, {:class => "btn btn-primary"} %>
  </div>
</div>

<div class='modal hide' id='add-value-confirm'>
  <div class='modal-header'>
    <a class='close' data-dismiss="modal">x</a>
    <h3>Add Value</h3>
  </div>
  <div class='modal-body'>
    <form class="well">
      <label>Hash field</label>
      <input type="text" class="span3" id="hash_field_input">
      <label>Hash Value</label>
      <input type="text" class="span3" id="hash_value_input">
    </form>
  </div>
  <div class='modal-footer'>
    <button class='btn btn-secondary' id='add-value-cancel-btn'>Cancel</button>
    <button class='btn btn-primary' id='add-value-confirm-btn'>Submit</button>
  </div>
</div>


<script type='text/javascript'>
  $('#add-value').click(function() {
    $('#add-value-confirm').modal({
      backdrop: true,
      keyboard: true
    });
  });

  $('#add-value-cancel-btn').click(function(){
    $('#add-value-confirm').modal('hide');
  });

  $('#add-value-confirm-btn').click(function() {
    var id = <%= @redishash.id %>;
    var field = document.getElementById("hash_field_input").value;
    var value = document.getElementById("hash_value_input").value;
    $.ajax({
      url     : 'add_redis_value?value='+value+'&field='+field+'&id='+id,
      success : function(){
        $('#add-value-confirm').modal('hide');
         window.location.reload();
      }
    });
  });
    
  //////////////////////////////////////////////////////////////////////
  // encapsulate the config widget
  var configWidget = (function() {
    function render(data) {
      $('#config-table .editable').each(function() {
        var editable = $(this)
          , field = editable.attr('id');
        var redishash_id = <%= @redishash.id %>;

        var config = {
          url           : '/redishashes/' + redishash_id + '/save_redis_value',
          element_id    : 'id',
          params        : 'field='+ field,
          update_value  : 'value',
          show_buttons  :  true,
          save_button   : '<button style="margin-left:5px;"class="btn btn-primary">Save</button>',
          cancel_button : '<button class="btn">Cancel</button>',
          default_text  : '&nbsp'
        };

        editable.editInPlace(config);
      });
    }

    return {
      render: render
    }
  })();

  configWidget.render()
</script>

app/views/redishashes/index.html.erb
<h1>Redis Hash</h1>
<form class="navbar-search pull-right"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
  <span id='filters_box'></span>
  <hr class='filters_box' style='display:none'>
  <input type="search" name="query" class="input-small" placeholder="Search.."><button style="margin-bottom:8px;" class="btn btn-primary" data-disable-with="<i class='icon-white icon-refresh'></i> Refresh" type="submit"><i class="icon-white icon-refresh"></i>Click</button>
</form>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
      <th>Type</th>
      <th>Size</th>
      <th>TTL</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @redishashes.each do |product| %>
      <tr>
        <td><%= link_to product.redis_key, redishash_path(product) %></td>
        <td><%= product.redis_value %></td>
        <td><%= product.redis_type %></td>
        <td><%= product.redis_value.try(:size) %></td>
        <td><%= product.ttl %></td>
        <td><%= time_ago_in_words product.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_redishash_path(product), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', redishash_path(product), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @redishashes, :theme => 'boot' %>

<%= link_to 'New', new_redishash_path, :class => 'btn btn-primary' %>

app/views/redishashes/new.html.erb
<%= render :partial => 'form' %>

app/views/redishashes/show.html.erb
<h1>Redis Hash</h1>

<fieldset>
  <dl>
    <dt class="key_field label string_type"><label>Key<dd><pre class="prettyprint"><%= @redishash.redis_key %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>Value<dd><pre class="prettyprint"><%= @redishash.redis_value %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>Type<dd><pre class="prettyprint"><%= @redishash.redis_type %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>Size<dd><pre class="prettyprint"><%= @redishash.redis_value.size %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>TTL<dd><pre class="prettyprint"><%= @redishash.ttl %></dd></pre></label></dt>
  </dl>
</fieldset>

<div class="form-actions">
  <%= link_to 'Back', redishashes_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_redishash_path(@redishash), :class => 'btn' %>
  <%= link_to 'Delete', redishash_path(@redishash), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>