config/routes.rb
Digg::Application.routes.draw do
  resources :redishashes do
    member do
      post "save_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :stringlists

  resources :objecteds do
    member do
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :records do
    member do
      post "save_redis_value"
      get "edit_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :products do
    member do
      post "save_redis_value"
      get "edit_redis_value"
      get "destroy_redis_value"
      get "add_redis_value"
    end
  end

  resources :redis_infos do
    collection do
      get "export"
      get "import"
      get 'index'
      get 'graph'
      get 'terminal'
      post 'configuration'
      get 'load_redis'
    end
  end

  resources :twitters do
    collection do
      get "init_data"
      get "index"
      get "remove_friend"
      get "add_post"
      get "add_friend"
    end
  end

  root :to => 'redis_infos#index'

end

app/models/product.rb
class Product < Record
  attr_accessible :redis_value

  def redis_value
    Redis.current.lrange(self.redis_key, 0, -1).join(",")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET /products
  # GET /products.json
  def index
    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis List", "/products"
    
    if params[:query]
      @products = Product.where("name like ?", "%"+params[:query]+"%").page(params[:page])
    else
      @products = Product.page params[:page]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis List", "/products"
    add_breadcrumb "#{@product.redis_key}", "/products/#{@product.id}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])

    add_breadcrumb "Dashboard", "/redis_infos"
    add_breadcrumb "Redis List", "/products"
    add_breadcrumb "#{@product.redis_key}", "/products/#{@product.id}"
  end

  # POST /products
  # Redis_value必须要在product创建之后commit，但之前必须过滤掉改值，因为会执行redis_value的写操作
  def create
    value = params[:product].except "redis_value"
    @product = Product.new(value)

    respond_to do |format|
      if @product.save

        # Redis 执行原子性操作，事务
        Redis.current.multi
        params[:product][:redis_value].split(",").each do |v|
          Redis.current.rpush(@product.redis_key, v)
        end
        Redis.current.exec
        # 结束事务操作

        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        @product.redis_value = params[:product][:redis_value]
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # 对非空列表进行 LSET
  #redis> LPUSH job "cook food"
  #(integer) 1
  #redis> LRANGE job 0 0
  #1) "cook food"
  #redis> LSET job 0 "play game"
  #OK
  #redis> LRANGE job  0 0
  #1) "play game"
  #
  def edit_redis_value
    @product = Product.find(params[:id]) 
    @value = @product.redis_value.split(",")[params[:index].to_i]
   #key = Product.find(params[:id]).redis_key
   #Redis.current.lset(key, params[:index], params[:value])
  end

  def save_redis_value
    @product = Product.find(params[:id]) 
    Redis.current.lset(@product.redis_key, params[:index], params[:value])

    render :text => params[:value] 
  end

  def add_redis_value
    @product = Product.find(params[:id]) 
    Redis.current.rpush(@product.redis_key, params[:value])

    respond_to do |format|
      format.html { redirect_to @product, notice: 'Value was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def destroy_redis_value
    @product = Product.find(params[:id]) 
    Redis.current.lrem(@product.redis_key, params[:index], params[:value])

    respond_to do |format|
      format.html { redirect_to edit_product_path, notice: 'Value was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    Redis.current.del @product.redis_key
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Redis List</legend>

    <div class="control-group">
      <%= f.label "key", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label "Value", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :redis_value, :class => 'text_area', :placeholder => "以逗号分割" %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', products_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/products/edit.html.erb
<h4>Key : <%= @product.redis_key %></h4>
<table class="table table-condensed">
  <tbody>
    <tr>
      <td style="width: 30%">Type</td>
      <td><%= @product.type %></td>
    </tr>
    <tr>
      <td style="width: 30%">TTL</td>
      <td><%= @product.ttl %></td>
    </tr>
    <tr>
      <td style="width: 30%">Encoding</td>
      <td><%= "Redis List" %></td>
    </tr>
    <tr>
      <td style="width: 30%">Size</td>
      <td><%= @product.redis_value.split(',').size %></td>
    </tr>
  </tbody>
</table>

<div class="widget">
  <div class="header">
    <h4>Values</h4>
  </div>
  <table class="table condensed-table" id="config-table">
    <tbody>
      <% @product.redis_value.split(",").each_with_index do |v, index| %>
        <tr>
          <td style="width: 30%">Index:<%= index + 1 %></td>
          <td>
            <div class="editable" id=<%= index %>><%= v %></div>
          </td>
          <td>
            <%= link_to "Delete", {:action => "destroy_redis_value", :id => @product.id, :index => index, :value => v, :controller => :products}, :confirm => "Are you sure?" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="btns">
    <button class="btn btn-primary" id="add-value">Add Value</button>
    <%= link_to "Back", products_path, {:class => "btn btn-primary"} %>
  </div>
</div>

<div class='modal hide' id='add-value-confirm'>
  <div class='modal-header'>
    <a class='close' data-dismiss="modal">x</a>
    <h3>Add Value</h3>
  </div>
  <div class='modal-body'>
    <form class="well">
      <label>List Value</label>
      <input type="text" class="span3" id="redis_value_input">
    </form>
  </div>
  <div class='modal-footer'>
    <button class='btn btn-secondary' id='add-value-cancel-btn'>Cancel</button>
    <button class='btn btn-primary' id='add-value-confirm-btn'>Submit</button>
  </div>
</div>


<script type='text/javascript'>
  $('#add-value').click(function() {
    $('#add-value-confirm').modal({
      backdrop: true,
      keyboard: true
    });
  });

  $('#add-value-cancel-btn').click(function(){
    $('#add-value-confirm').modal('hide');
  });

  $('#add-value-confirm-btn').click(function() {
    var id = <%= @product.id %>;
    var value = document.getElementById("redis_value_input").value;
    $.ajax({
      url     : 'add_redis_value?value='+value+'&id='+id,
      success : function(){
        $('#add-value-confirm').modal('hide');
         window.location.reload();
      }
    });
  });
    
  //////////////////////////////////////////////////////////////////////
  // encapsulate the config widget
  var configWidget = (function() {
    function render(data) {
      $('#config-table .editable').each(function() {
        var editable = $(this)
          , index = editable.attr('id');
        var product_id = <%= @product.id %>;

        var config = {
          url           : '/products/' + product_id + '/save_redis_value',
          element_id    : 'id',
          params        : 'index='+ index,
          update_value  : 'value',
          show_buttons  :  true,
          save_button   : '<button style="margin-left:5px;"class="btn btn-primary">Save</button>',
          cancel_button : '<button class="btn">Cancel</button>',
          default_text  : '&nbsp'
        };

        editable.editInPlace(config);
      });
    }

    return {
      render: render
    }
  })();

  configWidget.render()
</script>

app/views/products/edit_redis_value.html.erb
<%= form_for @value, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <div class="control-group">
      <%= f.label "Index", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field @value, :class => 'text_field' %>
        <%= link_to 'Destroy', {:action => :destroy_redis_value, :id => @product.id, :value => f, :controller => :products}, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/products/index.html.erb
<h1>Redis List</h1>
<form class="navbar-search pull-right"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /></div>
  <span id='filters_box'></span>
  <hr class='filters_box' style='display:none'>
  <input type="search" name="query" class="input-small" placeholder="Search.."><button style="margin-bottom:8px;" class="btn btn-primary" data-disable-with="<i class='icon-white icon-refresh'></i> Refresh" type="submit"><i class="icon-white icon-refresh"></i>Click</button>
</form>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
      <th>Type</th>
      <th>Size</th>
      <th>TTL</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.redis_key, product_path(product) %></td>
        <td><%= truncate product.redis_value %></td>
        <td><%= product.redis_type %></td>
        <td><%= Redis.current.lrange(product.redis_key, 0, -1).size %></td>
        <td><%= product.ttl %></td>
        <td><%= time_ago_in_words product.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_product_path(product), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', product_path(product), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @products, :theme => 'boot' %>

<%= link_to 'New', new_product_path, :class => 'btn btn-primary' %>

app/views/products/show.html.erb
<h1>Redis List</h1>

<fieldset>
  <dl>
    <dt class="key_field label string_type"><label>Key<dd><pre class="prettyprint"><%= @product.redis_key %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>Value<dd><pre class="prettyprint"><%= @product.redis_value %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>Type<dd><pre class="prettyprint"><%= @product.redis_type %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>Size<dd><pre class="prettyprint"><%= Redis.current.lrange(@product.redis_key, 0, -1).size %></dd></pre></label></dt>
    <dt class="value_field label string_type"><label>TTL<dd><pre class="prettyprint"><%= @product.ttl %></dd></pre></label></dt>
  </dl>
</fieldset>

<div class="form-actions">
  <%= link_to 'Back', products_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_product_path(@product), :class => 'btn' %>
  <%= link_to 'Delete', product_path(@product), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>